[tool.black]
line-length = 120

[tool.poetry]
name = "library-registry"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "CC0-1.0"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
invoke = "^1.7.1"
black = "^22.6"
flake8 = "^5.0.3"
pep8-naming = "^0.13.1"
yamllint = "^1.27.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
